### ISSUE TITLE
ModuleNotFoundError: No module named 'zeus.tfops'; 'zeus' is not a package

### ISSUE THREAD

**Issue by edrickwong** [openai/glow#2]
I tried running the training script with:
```
mpiexec -n 4 python train.py --data_dir imagenet-tfr --problem imagenet --image_size=32
```

Which results in the following error:
```
Traceback (most recent call last):
  File "train.py", line 289, in <module>
    main(hps)
  File "train.py", line 123, in main
    import model
  File "/home/edrick/glow/model.py", line 4, in <module>
    import optim
  File "/home/edrick/glow/optim.py", line 2, in <module>
    import zeus.tfops as Z
ModuleNotFoundError: No module named 'zeus.tfops'; 'zeus' is not a package
Traceback (most recent call last):
  File "train.py", line 289, in <module>
    main(hps)
  File "train.py", line 123, in main
    import model
  File "/home/edrick/glow/model.py", line 4, in <module>
    import optim
  File "/home/edrick/glow/optim.py", line 2, in <module>
    import zeus.tfops as Z
ModuleNotFoundError: No module named 'zeus.tfops'; 'zeus' is not a package
50000 50 4
Train epoch size: 50176
Traceback (most recent call last):
  File "train.py", line 289, in <module>
    main(hps)
  File "train.py", line 123, in main
    import model
  File "/home/edrick/glow/model.py", line 4, in <module>
    import optim
  File "/home/edrick/glow/optim.py", line 2, in <module>
    import zeus.tfops as Z
ModuleNotFoundError: No module named 'zeus.tfops'; 'zeus' is not a package
```

I installed zeus using `pip install zeus` which gives me `zeus==0.1.1`

**Comment by udnaan** [comment]
Ditto here. The zeus that is available through pip has no relevance. It would be helpful if a requirements.txt was included.

**Comment by EndingCredits** [comment]
N.B: This may be a typo. Try replacing `import zeus.tfops as Z` with `import tfops as Z` in optim.py

**Comment by repletetop** [comment]
@EndingCredits 
remark line like these 
    #logdirs, _print = zeus.get_logdirs(['', '_ckpt'])
    logdirs="./log"
    _print=print
it work

**Comment by prafullasd** [comment]
Fixed the imports, added requirements.txt. Added a simple json logger too for train, test results. Try 
now with latest version :)
