### ISSUE TITLE
run 'python model.py' in the demo folder

### ISSUE THREAD

**Issue by linhanxiao** [openai/glow#28]
there is a error
File "model.py", line 88, in <module>
    tf.import_graph_def(graph_def_optimized)
  File "/home/lhx/miniconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/lhx/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 489, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'EdgeBias' in binary running on lhx-910. Make sure the Op and Kernel are registered in the binary running in this process.

**Comment by kkshmz** [comment]
I can confirm this on my side as well. 
Running Ubuntu 16.04. Anaconda3 env.

**Comment by linhanxiao** [comment]
pip install blocksparse-1.0.0-py2.py3-none-any.whl
python
import blocksparse

there is a error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lhx/miniconda3/lib/python3.6/site-packages/blocksparse/__init__.py", line 6, in <module>
    bs_module = load_op_library(os.path.join(get_data_files_path(), 'blocksparse_ops.so'))
  File "/home/lhx/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/lhx/miniconda3/lib/python3.6/site-packages/blocksparse/blocksparse_ops.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumES3_S3_S3_

**Comment by linhanxiao** [comment]
@kkshmz

**Comment by linhanxiao** [comment]
@prafullasd 
when i run 'python model.py' 
there is a error
File "model.py", line 88, in
tf.import_graph_def(graph_def_optimized)
File "/home/lhx/miniconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
return func(*args, **kwargs)
File "/home/lhx/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 489, in import_graph_def
graph._c_graph, serialized, options) # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'EdgeBias' in binary running on lhx-910. Make sure the Op and Kernel are registered in the binary running in this process.

**Comment by prafullasd** [comment]
Try using the unoptimized model, it doesnt need you to install blocksparse. Download it from `https://storage.googleapis.com/glow-demo/large3/graph_unoptimized.pb`, and then set `optimized=False` in `model.py`

**Comment by xunnv** [comment]
> Try using the unoptimized model, it doesnt need you to install blocksparse. Download it from `https://storage.googleapis.com/glow-demo/large3/graph_unoptimized.pb`, and then set `optimized=False` in `model.py`

You just tell him how to avoid this problem, but how not to solve it.
