### ISSUE TITLE
load graph_optimized.pb error  no EdgeBias???

### ISSUE THREAD

**Issue by zj360202** [openai/glow#30]
tf.import_graph_def(graph_def_optimized)  load graph_optimized.pb error
##########################################################################
tensorflow 1.8.0 error
hortatech@1080Ti:~/projects/glow/demo$ python server.py 
2018-07-24 18:11:15.266967: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-07-24 18:11:15.348810: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-07-24 18:11:15.349242: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.46GiB
2018-07-24 18:11:15.349256: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-07-24 18:11:15.529259: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-24 18:11:15.529301: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-07-24 18:11:15.529308: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-07-24 18:11:15.529496: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10119 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "server.py", line 1, in <module>
    import model
  File "/home/hortatech/projects/glow/demo/model.py", line 88, in <module>
    tf.import_graph_def(graph_def_optimized)
  File "/home/hortatech/miniconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/hortatech/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 489, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'EdgeBias' in binary running on 1080Ti. Make sure the Op and Kernel are registered in the binary running in this process.
#############################################################
tensorflow 1.7.0
hortatech@1080Ti:~/projects/glow/demo$ python server.py 
2018-07-24 19:07:14.947274: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-07-24 19:07:15.041920: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-07-24 19:07:15.044762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.46GiB
2018-07-24 19:07:15.044780: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-07-24 19:07:15.217369: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-24 19:07:15.217395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2018-07-24 19:07:15.217402: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2018-07-24 19:07:15.217590: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10121 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "server.py", line 1, in <module>
    import model
  File "/home/hortatech/projects/glow/demo/model.py", line 88, in <module>
    tf.import_graph_def(graph_def_optimized)
  File "/home/hortatech/miniconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/hortatech/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 570, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named EdgeBias in defined operations.

**Comment by prafullasd** [comment]
You need to pip install the blocksparse package, check install instructions in `./script.py`
