### ISSUE TITLE
How do use this demo in cpu?

### ISSUE THREAD

**Issue by hule123** [openai/glow#38]
Traceback (most recent call last):
  File "/home/hule/myself/project/workspace/glow/demo/server.py", line 1, in <module>
    from demo import model
  File "/home/hule/myself/project/workspace/glow/demo/model.py", line 85, in <module>
    graph_def_optimized.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message

**Comment by victorherbemontagne** [comment]
@hule123  I don't know your error but I use the demo on CPU and it's working
Check that you are using the right pretrained graph (graph_unoptimized.pb and not graph_optimized.pb). They are both downloadable from the same source
