### ISSUE TITLE
Failed to install blocksparse

### ISSUE THREAD

**Issue by mrgloom** [openai/glow#49]
```
pip install blocksparse-1.0.0-py2.py3-none-any.whl
Processing ./blocksparse-1.0.0-py2.py3-none-any.whl
Requirement already satisfied: numpy in /home/user/anaconda3/lib/python3.5/site-packages (from blocksparse==1.0.0) (1.14.3)
Requirement already satisfied: scipy in /home/user/anaconda3/lib/python3.5/site-packages (from blocksparse==1.0.0) (1.1.0)
Installing collected packages: blocksparse
Successfully installed blocksparse-1.0.0

python
Python 3.5.5 |Anaconda, Inc.| (default, May 13 2018, 21:12:35)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import blocksparse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda3/lib/python3.5/site-packages/blocksparse/__init__.py", line 6, in <module>
    bs_module = load_op_library(os.path.join(get_data_files_path(), 'blocksparse_ops.so'))
  File "/home/user/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/user/anaconda3/lib/python3.5/site-packages/blocksparse/blocksparse_ops.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumES3_S3_S3_
```

**Comment by blengerich** [comment]
@mrgloom Were you able to resolve this? I'm having the same error.

**Comment by xunnv** [comment]
Same issue!
Searching for a solution for a long time, but still don't know how to resolve it.
